apps/career/urls.py
from django.urls import path

from . import views

app_name = 'career'
urlpatterns = [
    path('quarter/', views.quarter_list, name='quarter_list'),
    path('quarter/create/', views.quarter_create, name='quarter_create'),
    path('quarter/<int:q_id>/details/', views.quarter_details, name='quarter_details'),
    path('quarter/<int:q_id>/update/', views.quarter_update, name='quarter_update'),
    path('quarter/<int:q_id>/delete/', views.quarter_delete, name='quarter_delete'),

    path('level/', views.LevelListView.as_view(), name='level_list'),
    path('level/create/', views.LevelCreateView.as_view(), name='level_create'),
    path('level/<int:pk>/details', views.LevelDetailView.as_view(), name='level_detail'),
    path('level/<int:pk>/update', views.LevelUpdateView.as_view(), name='level_update'),
    path('level/<int:pk>/delete', views.LevelDeleteView.as_view(), name='level_delete'),
]

apps/home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact')
]

siiut/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls')),
    path('career/', include('apps.career.urls')),
]

apps/career/models.py
from django.db import models

from django.contrib.auth.models import User

class Quarter(models.Model):
    quarter = models.IntegerField(verbose_name='Cuatrimestre No')
    quarter_name = models.CharField(verbose_name='Cuatrimestre', max_length=20)

    def __str__(self):
        return self.quarter_name
    
    class Meta:
        verbose_name = 'Cuatrimestre'


class Level(models.Model):
    name = models.CharField(max_length=50, verbose_name='Nivel')
    short_name = models.CharField(max_length=10, verbose_name='Abreviatura')

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Nivel'
        verbose_name_plural = 'Niveles'


class Career(models.Model):
    name = models.CharField(max_length=100,
                            verbose_name='Nombre' )
    short_name = models.CharField(max_length=10,
                            verbose_name='Abreviatura')
    level = models.ForeignKey(Level, on_delete=models.CASCADE,
                            null=True, blank=True,
                            verbose_name='Nivel', related_name='careers')
    is_active = models.BooleanField(verbose_name='Activa?', 
                            default=True)
    principal = models.ForeignKey(User, on_delete=models.SET_NULL,
                            null=True, blank=True, related_name='careers',
                            verbose_name='Director de Carrera')
    year = models.CharField(max_length=4, verbose_name='Año')

    def __str__(self):
        return f"{ self.level } - { self.name }"
    
    class Meta:
        verbose_name = 'Carrera'


class Subject(models.Model):
    career = models.ForeignKey(Career, verbose_name='Carrera',
                               on_delete=models.CASCADE, related_name='subjects')
    quarter = models.ForeignKey(Quarter, verbose_name='Cuatrimestre',
                                on_delete=models.CASCADE, related_name='subjects')
    name = models.CharField(max_length=100, verbose_name='Materia')
    total_hours = models.IntegerField(verbose_name='Horas Totales')
    weekly_hours = models.IntegerField(verbose_name='Horas por Semana')
    # file: Para guardar la hoja de asignatura

    def __str__(self):
        return f"{ self.career.short_name } - { self.quarter } - { self.name }"
    
    class Meta:
        verbose_name = 'Materia'

apps/home/models.py
from django.db import models

# Create your models here.

apps/career/forms.py
from django import forms

from .models import Quarter

class QuarterForm(forms.ModelForm):
    class Meta:
        model = Quarter
        fields = ['quarter', 'quarter_name']
        widgets = {
            'quarter': forms.TextInput(attrs={"type": "number", "class": 'border border-gray-300 p-2 rounded-xl'}),
            'quarter_name': forms.TextInput(attrs={"class": 'border border-gray-300 p-2 rounded-xl'})
        }

apps/career/views.py
from django.shortcuts import render, redirect, HttpResponse

from .models import Quarter, Level
from .forms import QuarterForm
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

## CRUD Views for Quarter
def quarter_list(request):
    quarters = Quarter.objects.all()
    context = {
        "quarters": quarters
    }
    return render(request, 'career/quarter/index.html', context)

def quarter_create(request):
    if request.method == 'POST':
        form = QuarterForm(request.POST)
        if form.is_valid():
            quarter = Quarter(
                quarter = form.cleaned_data['quarter'],
                quarter_name = form.cleaned_data['quarter_name']
            )
            quarter.save()
            return redirect('career:quarter_list')
    else:
        form = QuarterForm()
        return render(request, 
                'career/quarter/create.html',
                {'form': form})

def quarter_details(request, q_id):
    quarter = Quarter.objects.get(pk=q_id)
    return render(request, 
            'career/quarter/details.html',
            {'quarter': quarter})

def quarter_update(request, q_id):
    q = Quarter.objects.get(pk=q_id)
    if request.method == 'POST':
        form = QuarterForm(request.POST)
        if form.is_valid():
            q.quarter = form.cleaned_data['quarter']
            q.quarter_name = form.cleaned_data['quarter_name']
            q.save()
            return redirect('career:quarter_list')
        else:
            return HttpResponse('Hay error en el formulario')
    else:
        form = QuarterForm(instance=q)
        return render(request, 
                    'career/quarter/update.html',
                    {'form': form})

def quarter_delete(request, q_id):
    if request.method == 'POST':
        q = Quarter.objects.get(pk=q_id)
        q.delete()
        return redirect('career:quarter_list')
    

### Vistas Basadas en Clases para Level Model
class LevelListView(ListView):
    model = Level
    template_name = 'career/level/index.html'
    context_object_name = 'levels'

class LevelDetailView(DetailView):
    model = Level
    template_name = 'career/level/details.html'
    context_object_name = 'level'

class LevelCreateView(CreateView):
    model = Level
    fields = ['name', 'short_name']
    template_name = 'career/level/create.html'
    success_url = reverse_lazy('career:level_list')

class LevelUpdateView(UpdateView):
    model = Level
    fields = ['name', 'short_name']
    template_name = 'career/level/update.html'
    success_url = reverse_lazy('career:level_list')

class LevelDeleteView(DeleteView):
    model = Level
    success_url = reverse_lazy('career:level_list')

apps/home/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home/index.html')

def about(request):
    return render(request, 'home/about.html')

def contact(request):
    return render(request, 'home/contact.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SIUUT 2025 | {% block title %}{% endblock %}</title>
    <script src="https://unpkg.com/@tailwindcss/browser@4"></script>
</head>
<body>
    {% include 'shared/header.html' %}
    <div class="px-6 py-2 flex gap-4">
        {% include 'shared/menu.html' %}
        <main class="container">
            {% block content %}
            {% endblock %}
        </main>
    </div>
</body>
</html>

templates/career/level/create.html
{% extends 'base.html' %}

{% block title %}Nuevo Nivel{% endblock title %}

{% block content %}
<h1>Nuevo Nivel</h1>    
<form method="post">
    {% csrf_token %}
    {{ form }}
    <input 
        class="py-2 cursor-pointer px-4 bg-green-300 hover:bg-green-700 rounded-xl"
        type="submit" value="Guardar">
</form>
{% endblock content %}
    
    

templates/career/level/details.html
{% extends 'base.html' %}

{% block title %}Detalles de Nivel{% endblock title %}

{% block content %}
<h1 class="text-2xl font-extrabold">Detalles de Nivel</h1>
<p>Nivel: {{ level.name }}</p>
<p>Abreviatura: {{ level.short_name }}</p>
<hr>
<a href="{% url 'career:level_update' level.id %}">Actualizar</a>
<form action="{% url 'career:level_delete' level.id %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Eliminar">
</form>
{% endblock content %}

templates/career/level/index.html
{% extends 'base.html' %}

{% block title %}Lista de Niveles{% endblock title %}

{% block content %}
<h1 class="text-2xl font-extrabold">Niveles</h1>
<a 
    class="py-2 cursor-pointer px-4 bg-green-300 hover:bg-green-700 rounded-xl"
    href="{% url 'career:level_create' %}">Nuevo Nivel</a>
<table>
    <thead>
        <tr>
            <th>Id</th>
            <th>Nivel</th>
            <th>Abreviatura</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% for level in levels %}
        <tr>
            <td><a href="{% url 'career:level_detail' level.id %}">{{ level.id }}</a></td>
            <td>{{ level.name }}</td>
            <td>{{ level.short_name }}</td>
            <td>Acciones</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}
    

templates/career/level/update.html
{% extends 'base.html' %}

{% block title %}Nuevo Nivel{% endblock title %}

{% block content %}
<h1>Nuevo Nivel</h1>    
<form method="post">
    {% csrf_token %}
    {{ form }}
    <input 
        class="py-2 cursor-pointer px-4 bg-green-300 hover:bg-green-700 rounded-xl"
        type="submit" value="Actualizar">
</form>
{% endblock content %}
    
    

templates/career/quarter/create.html
{% extends 'base.html' %}

{% block title %}Nuevo Cuatrimestre{% endblock title %}
    
{% block content %}
<h1 class="text-2xl font-extrabold">Nuevo Cuatrimestre</h1>
<form method="post">
    {% csrf_token %}
    <div class="flex justify-between mb-2">
        {{ form.quarter.label }}
        {{ form.quarter }}
    </div>
    <div class="flex justify-between mb-2">
        {{ form.quarter_name.label }}
        {{ form.quarter_name }}
    </div>
    <input 
        class="py-2 w-full cursor-pointer px-4 bg-green-300 hover:bg-green-700 rounded-xl"
        type="submit" 
        value="Guardar">
</form>
{% endblock content %}

templates/career/quarter/details.html
{% extends 'base.html' %}

{% block title %}Detalles de Cuatri{% endblock title %}

{% block content %}
<div>
    <h1>Detalles de {{ quarter }}</h1>
    <p>{{ quarter.quarter }}</p>
    <p>{{ quarter.quarter_name }}</p>
    <a href="{% url 'career:quarter_update' quarter.id %}">Actualizar</a>
    <form action="{% url 'career:quarter_delete' quarter.id %}" method="post">
        {% csrf_token %}
        <button type="submit" onclick="confirm('Seguro?')">Eliminar</button>
    </form>
    <a href="{% url 'career:quarter_list' %}">Regresar</a>
</div>
{% endblock content %}

templates/career/quarter/index.html
{% extends 'base.html' %}

{% block title %}Lista de Cuatrimestres{% endblock title %}

{% block content %}
<a 
class="py-2 cursor-pointer px-4 bg-green-300 hover:bg-green-700 rounded-xl"
href="{% url 'career:quarter_create' %}">Nuevo Cuatri</a>
<table>
    <thead>
        <tr>
            <th>id</th>
            <th>Quatrimestre No</th>
            <th>Quatrimestre</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% for quarter in quarters %}
        <tr>
            <td>{{ quarter.id }}</td>
            <td>{{ quarter.quarter }}</td>
            <td>{{ quarter.quarter_name }}</td>
            <td><a href="{% url 'career:quarter_details' quarter.id %}">Detalles</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table> 
{% endblock content %}
    
    

templates/career/quarter/update.html
{% extends 'base.html' %}

{% block title %}Actualiza Cuatrimestre{% endblock title %}
    
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Actualizar">
</form>
{% endblock content %}

templates/home/about.html
{% extends 'base.html' %}

{% block title %}Acerca de{% endblock title %}

{% block content %}
<h1>SIIUT 2025</h1>
<h2>Marco Antonio Damian Ortiz <a href="">@</a></h2>
{% endblock content %}

templates/home/contact.html
{% extends 'base.html' %}

{% block title %}Contacto{% endblock title %}

{% block content %}
<h1>Página de Contacto</h1>
{% endblock content %}

templates/home/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}
<h1>Sistema Integral de Información de las Universidades Tecnológicas</h1>
<a href="">Ingresar</a>
{% endblock content %}

templates/shared/header.html
<header class="bg-slate-500 text-white">
    <nav class="container mx-auto flex items-center justify-between py-4">
        <a href="" class="text-lg font-bold">SIIUT</a>
        <ul class="flex space-x-4">
            <li>
                <a href="">Login</a>
            </li>
            <li>
                <a href="">Logout</a>
            </li>
        </ul>
    </nav>
</header>

templates/shared/menu.html
<nav>
    <ul>
        <li>
            <a 
            class="block w-[200px] bg-slate-200 hover:bg-slate-400 m-2 rounded-xl p-2"
            href="{% url 'home:home' %}">Home</a>
        </li>
        <li>
            <a 
            class="block w-[200px] bg-slate-200 hover:bg-slate-400 m-2 rounded-xl p-2"
            href="{% url 'home:about' %}">Acerca de</a>
        </li>
        <li>
            <a 
            class="block w-[200px] bg-slate-200 hover:bg-slate-400 m-2 rounded-xl p-2"
            href="{% url 'home:contact' %}">Contacto</a>
        </li>
        <li>
            <a 
            class="block w-[200px] bg-slate-200 hover:bg-slate-400 m-2 rounded-xl p-2"
            href="{% url 'career:quarter_list' %}">Cuatrimestres</a>
        </li>
        <li>
            <a 
            class="block w-[200px] bg-slate-200 hover:bg-slate-400 m-2 rounded-xl p-2"
            href="{% url 'career:level_list' %}">Niveles</a>
        </li>
    </ul>
</nav>